apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: metadataexchange
  namespace: default
spec:
  priority: -1
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.tcp_proxy"
    patch:
      operation: INSERT_BEFORE
      value:
        name: "envoy.filters.network.metadata_exchange" # Not sure if matters
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: "type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange"
          value:
            protocol: mx-protocol
