apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: wtf-agent-alpn
  namespace: default
spec:
  priority: -1
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      # Seems to give the same result as ANY, except ANY causes 2 filter instances to be created
      # when a request is sent (but both instances have the same streamId.)
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: "istio.wtf_agent_alpn" # Not sure what the proxyStatsMatcher looks at; either this or the metadata name??
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: "type.googleapis.com/istio.envoy.config.filter.http.alpn.v2alpha1.FilterConfig"
