apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: wtf-agent-alpn
  namespace: default
spec:
  priority: -1
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: "istio.alpn" # Not sure if matters
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: "type.googleapis.com/istio.envoy.config.filter.http.alpn.v2alpha1.FilterConfig"
